import { Resend } from 'resend';

const resend = process.env.RESEND_API_KEY 
  ? new Resend(process.env.RESEND_API_KEY) 
  : null;

interface PassEmailOptions {
  to: string;
  visitorName: string;
  passId: string;
  passType: string;
  eventName: string;
  eventDate: string;
  eventVenue: string;
  qrCodeBase64: string;
}

export async function sendPassEmail(options: PassEmailOptions) {
  if (!process.env.RESEND_API_KEY) {
    console.warn("RESEND_API_KEY missing. Skipping email.");
    return;
  }

  try {
    if (!resend) return; 

    const { data, error } = await resend.emails.send({
      from: 'Pass Nexus <hello@passnexus.in>',
      to: [options.to],
      subject: `Your Pass for ${options.eventName} [${options.passId}]`,
      html: `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 40px; border: 1px solid #f0f0f0; border-radius: 24px;">
          <h1 style="font-size: 24px; font-weight: 800; color: #0f172a; margin-bottom: 8px;">Hello ${options.visitorName},</h1>
          <p style="color: #64748b; font-size: 16px; line-height: 1.6;">Your registration for <strong>${options.eventName}</strong> is confirmed. Below is your official digital pass.</p>
          
          <div style="background: #f8fafc; padding: 32px; border-radius: 20px; text-align: center; margin: 32px 0;">
            <p style="font-size: 10px; font-weight: 900; color: #3b82f6; text-transform: uppercase; letter-spacing: 0.2em; margin-bottom: 24px;">Scan this at the entrance</p>
            <img src="${options.qrCodeBase64}" width="200" height="200" style="border-radius: 12px; border: 4px solid #fff; box-shadow: 0 10px 15px -3px rgba(0,0,0,0.1);" />
            <p style="font-family: monospace; font-size: 12px; color: #94a3b8; margin-top: 24px; font-weight: bold;">${options.passId}</p>
          </div>

          <div style="margin-bottom: 32px;">
            <p style="font-size: 12px; font-weight: 900; color: #0f172a; text-transform: uppercase; letter-spacing: 0.1em; margin-bottom: 12px; border-bottom: 2px solid #f1f5f9; padding-bottom: 8px;">Event Details</p>
            <p style="margin: 8px 0; font-size: 14px; color: #475569;">📍 <strong>Venue:</strong> ${options.eventVenue}</p>
            <p style="margin: 8px 0; font-size: 14px; color: #475569;">📅 <strong>Date:</strong> ${options.eventDate}</p>
            <p style="margin: 8px 0; font-size: 14px; color: #475569;">🎫 <strong>Pass Type:</strong> ${options.passType}</p>
          </div>

          <p style="color: #94a3b8; font-size: 12px; text-align: center; margin-top: 40px;">
            This pass was generated by <strong>Pass Nexus</strong>. Please have it ready on your mobile device for a quick entry.
          </p>
        </div>
      `
    });

    if (error) throw error;
    return data;

  } catch (err) {
    console.error('Email Delivery Error:', err);
    throw new Error('Failed to send pass email');
  }
}
